-- Generate chain latency test data
-- Date: 2024-11-19

-- 1. Get existing chain ID
SET @chain_id = (SELECT id FROM chain_trace_config WHERE chain_name = 'user-service-chain' LIMIT 1);

-- 2. Get existing node IDs
SET @node1 = (SELECT id FROM chain_node_config WHERE chain_id = @chain_id ORDER BY sequence_order LIMIT 1);
SET @node2 = (SELECT id FROM chain_node_config WHERE chain_id = @chain_id ORDER BY sequence_order LIMIT 1 OFFSET 1);
SET @node3 = (SELECT id FROM chain_node_config WHERE chain_id = @chain_id ORDER BY sequence_order LIMIT 1 OFFSET 2);

-- 3. Clear old test data
DELETE FROM chain_latency_data WHERE chain_id = @chain_id;

-- 4. Generate data for Node 1 (API Gateway, latency 50-200ms)
INSERT INTO chain_latency_data (task_id, chain_id, node_id, request_id, node_name, request_start_time, request_end_time, latency, success, collection_time)
SELECT 
    1,
    @chain_id,
    @node1,
    CONCAT('REQ-GW-', LPAD(n, 6, '0')),
    'API-Gateway',
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    FLOOR(50 + RAND() * 150),
    IF(RAND() > 0.05, 1, 0),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR)
FROM (
    SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
    UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35
    UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
    UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45
    UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
    UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55
    UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60
    UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65
    UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70
    UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75
    UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80
    UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85
    UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90
    UNION SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95
    UNION SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100
) numbers;

-- 5. Generate data for Node 2 (User Service, latency 100-500ms)
INSERT INTO chain_latency_data (task_id, chain_id, node_id, request_id, node_name, request_start_time, request_end_time, latency, success, collection_time)
SELECT 
    1,
    @chain_id,
    @node2,
    CONCAT('REQ-US-', LPAD(n, 6, '0')),
    'User-Service',
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    FLOOR(100 + RAND() * 400),
    IF(RAND() > 0.03, 1, 0),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR)
FROM (
    SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
    UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35
    UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
    UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45
    UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
    UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55
    UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60
    UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65
    UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70
    UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75
    UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80
    UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85
    UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90
    UNION SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95
    UNION SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100
) numbers;

-- 6. Generate data for Node 3 (MySQL Database, latency 200-1000ms)
INSERT INTO chain_latency_data (task_id, chain_id, node_id, request_id, node_name, request_start_time, request_end_time, latency, success, collection_time)
SELECT 
    1,
    @chain_id,
    @node3,
    CONCAT('REQ-DB-', LPAD(n, 6, '0')),
    'MySQL-Database',
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    FLOOR(200 + RAND() * 800),
    IF(RAND() > 0.02, 1, 0),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR)
FROM (
    SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
    UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35
    UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
    UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45
    UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
    UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54 UNION SELECT 55
    UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59 UNION SELECT 60
    UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64 UNION SELECT 65
    UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69 UNION SELECT 70
    UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74 UNION SELECT 75
    UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79 UNION SELECT 80
    UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84 UNION SELECT 85
    UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89 UNION SELECT 90
    UNION SELECT 91 UNION SELECT 92 UNION SELECT 93 UNION SELECT 94 UNION SELECT 95
    UNION SELECT 96 UNION SELECT 97 UNION SELECT 98 UNION SELECT 99 UNION SELECT 100
) numbers;

-- 7. Fix timestamps
UPDATE chain_latency_data 
SET request_end_time = DATE_ADD(request_start_time, INTERVAL latency * 1000 MICROSECOND)
WHERE chain_id = @chain_id;

-- 8. Add error messages for failed requests
UPDATE chain_latency_data 
SET error_message = CASE 
    WHEN node_name LIKE '%Gateway%' THEN 'Gateway Timeout'
    WHEN node_name LIKE '%Service%' THEN 'Service Unavailable'
    WHEN node_name LIKE '%Database%' THEN 'Connection Timeout'
    ELSE 'Unknown Error'
END
WHERE success = 0 AND chain_id = @chain_id;

-- 9. Verify generated data
SELECT 
    'Statistics' as title,
    COUNT(*) as total_records,
    SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as success_count,
    SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) as failed_count,
    ROUND(AVG(latency), 2) as avg_latency_ms,
    MIN(latency) as min_latency_ms,
    MAX(latency) as max_latency_ms
FROM chain_latency_data
WHERE chain_id = @chain_id;

-- 10. Group by node
SELECT 
    node_name,
    COUNT(*) as record_count,
    MIN(latency) as min_latency,
    ROUND(AVG(latency), 2) as avg_latency,
    MAX(latency) as max_latency,
    SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as success_count,
    SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) as failed_count
FROM chain_latency_data
WHERE chain_id = @chain_id
GROUP BY node_name, node_id
ORDER BY node_id;

SELECT 'Test data generated successfully!' as status;
