-- 清空旧数据并生成新的测试数据
DELETE FROM chain_latency_data WHERE chain_id = 1;

-- 为节点1 (gateway) 生成50条数据
INSERT INTO chain_latency_data (task_id, chain_id, node_id, request_id, node_name, request_start_time, request_end_time, latency, success, collection_time)
SELECT 
    1, 1, 1,
    CONCAT('REQ-GW-', LPAD(n, 6, '0')),
    'gateway',
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    FLOOR(50 + RAND() * 150),
    IF(RAND() > 0.05, 1, 0),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR)
FROM (
    SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
    UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35
    UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
    UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45
    UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
) numbers;

-- 为节点2 (user-service) 生成50条数据
INSERT INTO chain_latency_data (task_id, chain_id, node_id, request_id, node_name, request_start_time, request_end_time, latency, success, collection_time)
SELECT 
    1, 1, 2,
    CONCAT('REQ-US-', LPAD(n, 6, '0')),
    'user-service',
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    FLOOR(100 + RAND() * 400),
    IF(RAND() > 0.03, 1, 0),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR)
FROM (
    SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
    UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35
    UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
    UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45
    UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
) numbers;

-- 为节点3 (mysql-db) 生成50条数据
INSERT INTO chain_latency_data (task_id, chain_id, node_id, request_id, node_name, request_start_time, request_end_time, latency, success, collection_time)
SELECT 
    1, 1, 3,
    CONCAT('REQ-DB-', LPAD(n, 6, '0')),
    'mysql-db',
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR),
    FLOOR(200 + RAND() * 800),
    IF(RAND() > 0.02, 1, 0),
    DATE_SUB(NOW(), INTERVAL FLOOR(RAND() * 24) HOUR)
FROM (
    SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
    UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35
    UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
    UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45
    UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
) numbers;

-- 修正时间戳
UPDATE chain_latency_data 
SET request_end_time = DATE_ADD(request_start_time, INTERVAL latency * 1000 MICROSECOND)
WHERE chain_id = 1;

-- 添加错误信息
UPDATE chain_latency_data 
SET error_message = CASE 
    WHEN node_name = 'gateway' THEN 'Gateway Timeout'
    WHEN node_name = 'user-service' THEN 'Service Unavailable'
    WHEN node_name = 'mysql-db' THEN 'Connection Timeout'
END
WHERE success = 0 AND chain_id = 1;

-- 显示结果
SELECT 
    node_name,
    COUNT(*) as record_count,
    MIN(latency) as min_latency_ms,
    ROUND(AVG(latency), 2) as avg_latency_ms,
    MAX(latency) as max_latency_ms,
    SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) as success_count,
    SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) as failed_count
FROM chain_latency_data
WHERE chain_id = 1
GROUP BY node_name, node_id
ORDER BY node_id;
